JavaScript IR Support
JuulLabs/kable pull request #126
Opened 2021-06-26 05:19 UTC by KVelasco

Resolves #106

2021-06-26 06:18 UTC, twyatt approved these changes
Thanks!

2021-06-28 17:19 UTC, cedrickcooke approved these changes

2021-06-28 17:56 UTC, twyatt requested changes
Marking `request changes` to make sure [sample app](https://github.com/JuulLabs/sensortag) is updated to validate this change before we merge.

2021-07-01 17:23 UTC, twyatt approved these changes

2021-07-02 14:34 UTC, merged