Only set `pending` flag on success and reset on cancellation
JuulLabs/kable pull request #453
Opened 2023-04-05 18:44 UTC by twyatt

Closes #450

2023-04-06 12:33 UTC, matejbart requested changes

2023-04-07 17:59 UTC, twyatt commented on core/src/appleMain/kotlin/Connection.kt
>          action.invoke()
Good catch! I've swapped the lines and went with your suggested `awaitingResponse` naming. Thanks!

2023-04-07 18:24 UTC, twyatt commented on core/src/androidMain/kotlin/Connection.kt
> +                callback.onResponse.receive()
> Unfortunately, if a CancellationException is thrown here

I've changed this to use `tryReceive` to essentially "clear" the `onResponse` channel (to discard any awaiting responses). `tryReceive` is not `suspend`ing so (my understanding) is that it wouldn't throw a `CancellationException`.

> the `receive()` call to the channel could be performed in an own coroutine scope & job

I like your suggestion of using a `Job` to grab the response, but I'd like to try a bit more with the current approach, as to not make major changes and (hopefully) this is a slightly simpler approach. 🤷 

I'll use a `Job` if I've exhausted ideas around using a `boolean` flag.

2023-04-10 08:10 UTC, matejbart commented on core/src/androidMain/kotlin/Connection.kt
> +                callback.onResponse.receive()
Correct me if I'm wrong, but i think that the usage of `tryReceive` still doesn't guarantee a "discard" of a response in the `onResponse` Channel: it's a non-suspending operation, so if `onResponse` is empty at that time (the case when the previous request's response has still not be sent to `onResponse` which can very likely happen), then `tryReceive` will still immediately return with a failed result. As a consequence, the next time we run into `receive()` we still get the wrong response. `tryReceive` would only help us if the response would be already present in the `Channel` but which is something we cannot assume.

I.e. the deadlocks issue would be solved, but unfortunately the bug that has been fixed in #326 would be re-introduced again. 

A simplified version (without error handling etc) of how we could use a `Deferred` in the `execute` func to basically never cancel a `onReceive` call (for an active ongoing connection):

```
private suspend inline fun execute(request: () -> Boolean) = lock.withLock {
    // try to await a still active deferred to not mix up the responses
    // of previous request attempts
    deferredResponse?.let {
        if (it.isActive) {
            // discard the result of the previous request
            it.await()
        }
    }
    // run the request
    if(!request()) {
        // throw an exception if it has not been sent out successfully
        throw IllegalStateException()
    }
    // prepare to receive a value from the onResponse channel
    val deferred = receiveScope.async {
        onResponse.receive()
    }
    // keep the reference and start the job.
    deferredResponse = deferred
    return@withLock deferred.await()
}
```

where `receiveScope` would be simply the current `Peripheral`'s `scope`.

2023-04-10 08:12 UTC, matejbart commented on core/src/appleMain/kotlin/Connection.kt
>          action.invoke()
looks good 👍

2023-04-11 03:16 UTC, twyatt commented on core/src/androidMain/kotlin/Connection.kt
> +                callback.onResponse.receive()
> Correct me if I'm wrong, but i think that the usage of `tryReceive` still doesn't guarantee a "discard" of a response in the `onResponse` Channel: it's a non-suspending operation, so if `onResponse` is empty at that time (the case when the previous request's response has still not be sent to `onResponse` which can very likely happen), then `tryReceive` will still immediately return with a failed result.

Ya, looking at it again, you're right.

> A simplified version (without error handling etc) of how we could use a `Deferred` in the `execute` func to basically never cancel a `onReceive` call (for an active ongoing connection)

Thanks for this! My initial hesitation with this approach was the added complexity and potential performance impacts. So, I benchmarked the `async` operation (on a Pixel 6a, using `androidx.benchmark:benchmark-junit4`) and the results:

```
495   ns           5 allocs    trace    AsyncBenchmark.async
```

Ultimately, 495ns is negligible (especially compared to the BLE I/O it is managing), and 5 object allocations isn't going to hurt.

After discussing internally with the team, we concur that your approach would be better moving forward. I'll be making the changes and pushing them soon.

Thanks so much for all your help!

2023-04-11 11:43 UTC, matejbart commented on core/src/androidMain/kotlin/Connection.kt
> +                callback.onResponse.receive()
I understand your concerns about the complexity, thx for the benchmarks. The changes are good.

2023-04-11 11:44 UTC, matejbart approved these changes

2023-04-12 17:43 UTC, davidtaylor-juul approved these changes
🚀

2023-04-13 18:55 UTC, cedrickcooke approved these changes
New impl feels robust, love it

2023-04-17 05:41 UTC, merged